### PR TITLE
Removed GA tracking code

### PR DESCRIPTION
**Pull request by shinsenter**
Removed GA tracking code due to WordPress Plugin Directory guidelines

### CODE REVIEW

**Comment by andresgutgon** [comment]
Why did you wanted to track Analytics on others' people Wordpress? 😅

**Comment by shinsenter** [comment]
@andresgutgon 
No, certainly not!

That was the story of about 2 years ago.

I just wanted to track if the admins have opened the plugin settings and to gauge their interest in this plugin. However I removed it afterwards. 🙃

**Comment by andresgutgon** [comment]
Ok nice. Because of this I'm trying to move from 1.1.10 to 1.1.11 but composer doesn't allow it

// My composer.json
image

The error
image


And the plugin where it looks `1.1.11` is there https://wpackagist.wpsv.se/search?q=shins-pageload-magic&type=any&search=

Any idea of why this could happen?

**Comment by shinsenter** [comment]
@andresgutgon 
Oh really?  Don't you know that this plugin is up to version 2.x already?

**Comment by andresgutgon** [comment]
> Oh really? Don't you know that this plugin is up to version 2.x already?

I don't want to do the migration today 😅

**Comment by shinsenter** [comment]
> > Oh really? Don't you know that this plugin is up to version 2.x already?
> 
> I don't want to do the migration today 😅

So pls do it on another day

**Pull request merged**
